"""List of all log data extract available in the CARWatch App."""
# log extras
subject_id: str = "subject_id"
subject_condition: str = "subject_condition"
alarm_id: str = "id"
saliva_id: str = "saliva_id"
barcode_value: str = "barcode_value"
timestamp: str = "timestamp"
is_hidden: str = "is_hidden"
hidden_timestamp: str = "hidden_timestamp"
is_repeating: str = "is_repeating"
repeating_days: str = "repeating_days"
snooze_duration: str = "snooze_duration"
source: str = "source"
other_barcodes: str = "other_barcodes"
day_counter: str = "day_counter"
app_version_code: str = "version_code"
app_version_name: str = "version_name"
brand: str = "brand"
manufacturer: str = "manufacturer"
model: str = "model"
version_sdk_level: str = "version_sdk_level"
version_security_patch: str = "version_security_patch"
version_release: str = "version_release"
